services:
  - type: web
    name: file-vault
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python -c "from crypto import CryptoVault; CryptoVault('keys').generate_key_pair()"
    startCommand: gunicorn app:app --bind 0.0.0.0:10000
    envVars:
      - key: FLASK_ENV
        value: production
    plan: free
